### ISSUE TITLE
Change exit code if no files were scanned

### ISSUE THREAD

**Issue by DanielSchwiperich** [sebastianbergmann/phpcpd#147]
phpcpd is giving an exit code of 1 if no files were found to scan. 

This is different behaviour to similar tools like phpcs and phpmd. 
It would be nice to have that behaviour changed so that's in line with those other tools. 
(Useful in CI for example where the return values are evaluated and used to make a stage fail)

**Comment by renanmpimentel** [comment]
@DanielSchwiperich use:

```
phpcpd /path || echo 0
```

¯\_(ツ)_/¯

**Comment by DanielSchwiperich** [comment]
This will always return 0, also when files are scanned and errors / warnings are found. 
So not helpful but thx
> (Useful in CI for example where the return values are evaluated and used to make a stage fail)

**Comment by mvscheidt** [comment]
as @DanielSchwiperich said - the workaround as proposed in https://github.com/sebastianbergmann/phpcpd/issues/147#issuecomment-309073239 would work differently than what he wants

He wants the command to exit with code `0` (success) if

* there are no files to scan
* there are no clones in the scanned files

Of course the command should fail (as it already does) when clones have been found.

----

Currently the phpcd command has two `exit()` statements which both return `1`

* https://github.com/sebastianbergmann/phpcpd/blob/master/src/CLI/Command.php#L128 (no files found)
* https://github.com/sebastianbergmann/phpcpd/blob/master/src/CLI/Command.php#L173 (clones found)

Because both return code `1` you cannot separate the two - maybe if you log and parse the output to the console and check for `No files found to scan` additionally but that sounds rather dirty and convoluted.

----

IMO either exit with code `0` in case no files are found OR change the error code to `2` (or whatever number would be suitable - I am no expert on exit codes and the best practices).

On the other hand changing this behaviour seems to be a BC-Break to me because some people might actually expect "no files found" to return an error code - not sure what the stance of @sebastianbergmann on this is.

**Comment by mautz-et-tong** [comment]
Happens again in 6.0.3:
https://github.com/sebastianbergmann/phpcpd/blob/master/src/CLI/Application.php#L62

exit code is 1 when no files are found to scan.

If error code should be 0 as this was a bug in 2017, I can provide a PR.

**Comment by lukewhitmore** [comment]
I can confirm the same behaviour in 6.0.3.

**Comment by jklmnop** [comment]
i'm experiencing the same thing with 6.0.3
