### ISSUE TITLE
Option to exit with a zero code even if any violations are found.

### ISSUE THREAD

**Issue by pnikolov** [sebastianbergmann/phpcpd#148]
Such option will be useful in a report stage during a CI process. 
Currently each copy/paste detection will trigger a error exit code.
For example such option in phpmd is called `--ignore-violations-on-exit`.

**Comment by orlangur** [comment]
Just ignore `phpcpd` exit code then during report stage (I'm not sure why you need it at all if you ignore violations anyway).

There is nothing to do here from `phpcpd` side.

**Comment by pnikolov** [comment]
Yes, this is a possible solution, for example using:
`$ phpcpd ... || true` will ignore the exit code and will continue executing the next tasks.

But I personally like more elegant solution like passing `--ignore-violations-on-exit`.

**Comment by stephanvierkant** [comment]
``ignore-violations-on-exit`` would be an elegant solution. Just like phpmd:

https://github.com/phpmd/phpmd/blob/master/README.rst#user-content-command-line-options

> ``--ignore-violations-on-exit``- will exit with a zero code, even if any violations are found.

**Comment by TomasVotruba** [comment]
This would be great, since it fails on CI or checking multiple sources.

https://github.com/TomasVotruba/shopsys-analysis/issues/2

**Comment by orlangur** [comment]
@pnikolov @stephanvierkant why separate option is an "elegant solution" if the same behavior can be achieved pretty easily with less code (`|| true`)?

**Comment by TomasVotruba** [comment]
@orlangur I think using `|| true` is counter-intuitive solution to all other CI tools - PHPUnit, CodeSniffer, PHP-CS-Fixer, linter etc.

**Comment by sebastianbergmann** [comment]
I do not think that this would be useful.

**Comment by hakamairi** [comment]
Is there any was to distinguish between duplicate code found and a real issue basing on the status codes returned?
` || true` just ignores the exit code, right?

**Comment by dpalic** [comment]
@sebastianbergmann in CI/CD environments I need to know if I have an issue from anything else despite of the code issues.
In this case I need to be sure the build breaks. It would not if I append 
   || true
to the command

But it would if I could ensure that the exit code is only written if I want to have it
And in CI/CD environment I do not want that my build breaks and stops and does not generete the other metrics too. This only due to one lazy developer, who did not run prior checks locally.
So the 
   --ignore-violations-on-exit
like in phpmd would be a great help!
